// Generated by https://mholt.github.io/json-to-go/
package main

import "time"

type Broadcast struct {
	Href                 string        `json:"href"`
	Station              string        `json:"station"`
	Entity               string        `json:"entity"`
	ID                   int           `json:"id"`
	BroadcastDay         int           `json:"broadcastDay"`
	ProgramKey           string        `json:"programKey"`
	Program              string        `json:"program"`
	Title                string        `json:"title"`
	Subtitle             string        `json:"subtitle"`
	Ressort              string        `json:"ressort"`
	State                string        `json:"state"`
	IsOnDemand           bool          `json:"isOnDemand"`
	IsGeoProtected       bool          `json:"isGeoProtected"`
	IsAdFree             bool          `json:"isAdFree"`
	Start                int64         `json:"start"`
	StartISO             time.Time     `json:"startISO"`
	StartOffset          int           `json:"startOffset"`
	ScheduledStart       int64         `json:"scheduledStart"`
	ScheduledStartISO    time.Time     `json:"scheduledStartISO"`
	ScheduledStartOffset int           `json:"scheduledStartOffset"`
	End                  int64         `json:"end"`
	EndISO               time.Time     `json:"endISO"`
	EndOffset            int           `json:"endOffset"`
	ScheduledEnd         int64         `json:"scheduledEnd"`
	ScheduledEndISO      time.Time     `json:"scheduledEndISO"`
	ScheduledEndOffset   int           `json:"scheduledEndOffset"`
	NiceTime             int64         `json:"niceTime"`
	NiceTimeISO          time.Time     `json:"niceTimeISO"`
	NiceTimeOffset       int           `json:"niceTimeOffset"`
	Description          string        `json:"description"`
	PressRelease         string        `json:"pressRelease"`
	Moderator            string        `json:"moderator"`
	URL                  string        `json:"url"`
	Images               []Images      `json:"images"`
	Tags                 []interface{} `json:"tags"`
	Oe1Tags              []interface{} `json:"oe1tags"`
	Items                []Items       `json:"items"`
	Streams              []Streams     `json:"streams"`
	Marks                []Marks       `json:"marks"`
}
type Versions struct {
	Path     string `json:"path"`
	Width    int    `json:"width"`
	HashCode int    `json:"hashCode"`
}
type Images struct {
	Alt       string     `json:"alt"`
	Mode      string     `json:"mode"`
	Text      string     `json:"text"`
	Category  string     `json:"category"`
	HashCode  int        `json:"hashCode"`
	Versions  []Versions `json:"versions"`
	Copyright string     `json:"copyright"`
}
type Items struct {
	Href           string        `json:"href"`
	Station        string        `json:"station"`
	Entity         string        `json:"entity"`
	ID             int           `json:"id"`
	BroadcastDay   int           `json:"broadcastDay"`
	ProgramKey     string        `json:"programKey"`
	Program        string        `json:"program"`
	Type           string        `json:"type"`
	Description    string        `json:"description"`
	State          string        `json:"state"`
	IsOnDemand     bool          `json:"isOnDemand"`
	IsGeoProtected bool          `json:"isGeoProtected"`
	IsCompleted    bool          `json:"isCompleted"`
	Duration       int           `json:"duration"`
	Oe1Tags        []interface{} `json:"oe1tags"`
	Tags           []interface{} `json:"tags"`
	SongID         interface{}   `json:"songId"`
	IsAdFree       bool          `json:"isAdFree"`
	Title          string        `json:"title,omitempty"`
	Subtitle       string        `json:"subtitle,omitempty"`
	Moderator      string        `json:"moderator,omitempty"`
	Start          int64         `json:"start"`
	StartISO       time.Time     `json:"startISO"`
	StartOffset    int           `json:"startOffset"`
	End            int64         `json:"end"`
	EndISO         time.Time     `json:"endISO"`
	EndOffset      int           `json:"endOffset"`
}
type Streams struct {
	Alias        string    `json:"alias"`
	Title        string    `json:"title"`
	LoopStreamID string    `json:"loopStreamId"`
	Start        int64     `json:"start"`
	StartISO     time.Time `json:"startISO"`
	StartOffset  int       `json:"startOffset"`
	End          int64     `json:"end"`
	EndISO       time.Time `json:"endISO"`
	EndOffset    int       `json:"endOffset"`
}
type Marks struct {
	Type            string    `json:"type"`
	Timestamp       int64     `json:"timestamp"`
	TimestampISO    time.Time `json:"timestampISO"`
	TimestampOffset int       `json:"timestampOffset"`
}
