// Generated by https://mholt.github.io/json-to-go/
package main

import (
	"net/url"
	"strings"
	"time"
)

type Broadcast struct {
	Href                 string        `json:"href"`
	Station              string        `json:"station"`
	Entity               string        `json:"entity"`
	ID                   int           `json:"id"`
	BroadcastDay         int           `json:"broadcastDay"`
	ProgramKey           string        `json:"programKey"`
	Program              string        `json:"program"`
	Title                string        `json:"title"`
	Subtitle             string        `json:"subtitle"`
	Ressort              string        `json:"ressort"`
	State                string        `json:"state"`
	IsOnDemand           bool          `json:"isOnDemand"`
	IsGeoProtected       bool          `json:"isGeoProtected"`
	IsAdFree             bool          `json:"isAdFree"`
	Start                int64         `json:"start"`
	StartISO             time.Time     `json:"startISO"`
	StartOffset          int           `json:"startOffset"`
	ScheduledStart       int64         `json:"scheduledStart"`
	ScheduledStartISO    time.Time     `json:"scheduledStartISO"`
	ScheduledStartOffset int           `json:"scheduledStartOffset"`
	End                  int64         `json:"end"`
	EndISO               time.Time     `json:"endISO"`
	EndOffset            int           `json:"endOffset"`
	ScheduledEnd         int64         `json:"scheduledEnd"`
	ScheduledEndISO      time.Time     `json:"scheduledEndISO"`
	ScheduledEndOffset   int           `json:"scheduledEndOffset"`
	NiceTime             int64         `json:"niceTime"`
	NiceTimeISO          time.Time     `json:"niceTimeISO"`
	NiceTimeOffset       int           `json:"niceTimeOffset"`
	Description          string        `json:"description"`
	PressRelease         string        `json:"pressRelease"`
	Moderator            string        `json:"moderator"`
	URL                  string        `json:"url"`
	Images               []Images      `json:"images"`
	Tags                 []interface{} `json:"tags"`
	Oe1Tags              []interface{} `json:"oe1tags"`
	Items                []Items       `json:"items"`
	Streams              []Streams     `json:"streams"`
	Marks                []Marks       `json:"marks"`
}
type Versions struct {
	Path     string `json:"path"`
	Width    int    `json:"width"`
	HashCode int    `json:"hashCode"`
}
type Images struct {
	Alt       string     `json:"alt"`
	Mode      string     `json:"mode"`
	Text      string     `json:"text"`
	Category  string     `json:"category"`
	HashCode  int        `json:"hashCode"`
	Versions  []Versions `json:"versions"`
	Copyright string     `json:"copyright"`
}
type Items struct {
	Href           string        `json:"href"`
	Station        string        `json:"station"`
	Entity         string        `json:"entity"`
	ID             int           `json:"id"`
	BroadcastDay   int           `json:"broadcastDay"`
	ProgramKey     string        `json:"programKey"`
	Program        string        `json:"program"`
	Type           string        `json:"type"`
	Description    string        `json:"description"`
	State          string        `json:"state"`
	IsOnDemand     bool          `json:"isOnDemand"`
	IsGeoProtected bool          `json:"isGeoProtected"`
	IsCompleted    bool          `json:"isCompleted"`
	Duration       int           `json:"duration"`
	Oe1Tags        []interface{} `json:"oe1tags"`
	Tags           []interface{} `json:"tags"`
	SongID         interface{}   `json:"songId"`
	IsAdFree       bool          `json:"isAdFree"`
	Title          string        `json:"title,omitempty"`
	Subtitle       string        `json:"subtitle,omitempty"`
	Moderator      string        `json:"moderator,omitempty"`
	Start          int64         `json:"start"`
	StartISO       time.Time     `json:"startISO"`
	StartOffset    int           `json:"startOffset"`
	End            int64         `json:"end"`
	EndISO         time.Time     `json:"endISO"`
	EndOffset      int           `json:"endOffset"`
}
type Streams struct {
	Alias        string    `json:"alias"`
	Title        string    `json:"title"`
	LoopStreamID string    `json:"loopStreamId"`
	Start        int64     `json:"start"`
	StartISO     time.Time `json:"startISO"`
	StartOffset  int       `json:"startOffset"`
	End          int64     `json:"end"`
	EndISO       time.Time `json:"endISO"`
	EndOffset    int       `json:"endOffset"`
	// Progressive is the canonical sound.orf.at stream URL (per-station host,
	// e.g. loopstreamfm4.apa.at) for the loopStreamId, stripped of the v5.0
	// URI-template tokens and pre-filled offset range. getDownloadUrl returns
	// it verbatim; getSegmentUrl appends &offset/&offsetende. Populated from
	// the v5.0 payload by toBroadcast; not present in the v4.0 JSON.
	Progressive string `json:"-"`
}
type Marks struct {
	Type            string    `json:"type"`
	Timestamp       int64     `json:"timestamp"`
	TimestampISO    time.Time `json:"timestampISO"`
	TimestampOffset int       `json:"timestampOffset"`
}

// ---- v5.0 payload bridge ----
//
// The types below mirror the v5.0 broadcast payload served by
// audioapi.orf.at/{station}/api/json/5.0/broadcast/{id} - the same endpoint
// the sound.orf.at Vue SPA consumes. They are an intermediate only: getBroadcast
// parses the v5.0 JSON into broadcastV5, then toBroadcast maps it into the
// existing int64-millisecond Broadcast/Items/Streams model above so trim.go's
// segment arithmetic (item.Start - stream.Start) and the v4.0 test fixtures
// keep working unchanged.
//
// Coordinate convention (verified against the live API): the loopstream
// &offset/&offsetende params are expressed in milliseconds from the broadcast
// start (offset 0 = broadcast.start, offsetEnd = duration). The v4.0 API set
// streams[*].start to the broadcast start, so to match that - and keep
// trim.go's invariant item.Start - stream.Start == ms-from-broadcast-start -
// toBroadcast maps Streams[*].Start/End from the broadcast start/end, NOT from
// the stream's own music-only start/end.

type streamV5 struct {
	Host         string `json:"host"`
	Channel      string `json:"channel"`
	LoopStreamID string `json:"loopStreamId"`
	Start        string `json:"start"` // ISO = music stream start (> broadcast start)
	End          string `json:"end"`   // ISO
	OffsetStart  int64  `json:"offsetStart"`
	OffsetEnd    int64  `json:"offsetEnd"`
	Urls         struct {
		Progressive string `json:"progressive"`
		HLS         string `json:"hls"`
	} `json:"urls"`
	URITemplates struct {
		Progressive string `json:"progressive"`
		HLS         string `json:"hls"`
	} `json:"uriTemplates"`
}

type itemV5 struct {
	Type     string `json:"type"`
	Title    string `json:"title,omitempty"`
	Subtitle string `json:"subtitle,omitempty"`
	Start    string `json:"start"` // ISO
	End      string `json:"end"`   // ISO
	Duration int    `json:"duration"`
}

type broadcastV5 struct {
	Href           string     `json:"href"`
	Station        string     `json:"station"`
	ID             int        `json:"id"`
	BroadcastDay   int        `json:"broadcastDay"`
	ProgramKey     string     `json:"programKey"`
	Program        string     `json:"program"`
	Title          string     `json:"title"`
	Subtitle       string     `json:"subtitle"`
	PressRelease   string     `json:"pressRelease"`
	State          string     `json:"state"`
	IsOnDemand     bool       `json:"isOnDemand"`
	IsGeoProtected bool       `json:"isGeoProtected"`
	IsAdFree       bool       `json:"isAdFree"`
	Start          string     `json:"start"` // ISO
	End            string     `json:"end"`   // ISO
	Duration       int        `json:"duration"`
	Images         []Images   `json:"images"`
	Streams        []streamV5 `json:"streams"`
	Items          []itemV5   `json:"items"`
}

// toBroadcast maps the v5.0 payload into the consumed int64-ms Broadcast model.
// trim.go reads only Streams[0].Start/End and Items[*].Type/Start/End, so only
// those are carried over precisely; the rest is best-effort for logging.
func (b broadcastV5) toBroadcast() Broadcast {
	startMs := isoToMs(b.Start)
	endMs := isoToMs(b.End)
	startISO := isoToTime(b.Start)
	endISO := isoToTime(b.End)

	items := make([]Items, 0, len(b.Items))
	for _, it := range b.Items {
		items = append(items, Items{
			Type:     it.Type,
			Title:    it.Title,
			Subtitle: it.Subtitle,
			Start:    isoToMs(it.Start),
			End:      isoToMs(it.End),
			Duration: it.Duration,
		})
	}

	streams := make([]Streams, 0, len(b.Streams))
	for _, s := range b.Streams {
		streams = append(streams, Streams{
			LoopStreamID: s.LoopStreamID,
			// Stream Start/End mapped to the BROADCAST range, not the stream's
			// music-only range, so trim.go's item.Start - stream.Start resolves
			// to ms-from-broadcast-start (the loopstream &offset coordinate).
			Start:       startMs,
			End:         endMs,
			StartISO:    startISO,
			EndISO:      endISO,
			Progressive: cleanProgressiveURL(s.URITemplates.Progressive, s.Urls.Progressive),
		})
	}

	return Broadcast{
		Href:           b.Href,
		Station:        b.Station,
		ID:             b.ID,
		BroadcastDay:   b.BroadcastDay,
		ProgramKey:     b.ProgramKey,
		Program:        b.Program,
		Title:          b.Title,
		Subtitle:       b.Subtitle,
		PressRelease:   b.PressRelease,
		State:          b.State,
		IsOnDemand:     b.IsOnDemand,
		IsGeoProtected: b.IsGeoProtected,
		IsAdFree:       b.IsAdFree,
		Start:          startMs,
		End:            endMs,
		StartISO:       startISO,
		EndISO:         endISO,
		Images:         b.Images,
		Streams:        streams,
		Items:          items,
	}
}

// isoToTime parses an ORF v5.0 ISO-8601 timestamp (e.g.
// "2026-06-20T16:59:36.000Z"). Returns the zero time on failure; callers that
// branch on "" guard the empty case.
func isoToTime(iso string) time.Time {
	if iso == "" {
		return time.Time{}
	}
	t, err := time.Parse(time.RFC3339, iso)
	if err != nil {
		return time.Time{}
	}
	return t
}

// isoToMs parses an ORF v5.0 ISO-8601 timestamp to Unix epoch milliseconds.
func isoToMs(iso string) int64 {
	return isoToTime(iso).UnixMilli()
}

// cleanProgressiveURL reduces the v5.0 stream URL to a bare
// "?channel=<station>&id=<loopStreamId>" base that getDownloadUrl (whole
// stream) and getSegmentUrl (with &offset/&offsetende) can consume.
//
// The v5.0 payload ships the download URL in two forms, both suffixed with
// RFC-6570 {&shoutcast}{&player}{&referer}{&userid} tokens the server
// tolerates but we do not want in the request:
//   - urls.progressive:        ...?channel=...&id=...&offset=<start>&offsetende=<end>{&...}
//   - uriTemplates.progressive: ...?channel=...&id=...mp3{&offset}{&offsetende}{&...}
//
// Prefer the template (no pre-filled offset range); fall back to the expanded
// URL. Strip from the first '{', then drop the loopstream control params so
// the caller owns the offset range entirely.
func cleanProgressiveURL(progURL, template string) string {
	src := template
	if src == "" {
		src = progURL
	}
	if i := strings.IndexByte(src, '{'); i >= 0 {
		src = src[:i]
	}
	u, err := url.Parse(src)
	if err != nil {
		return src
	}
	q := u.Query()
	for _, k := range []string{"offset", "offsetende", "shoutcast", "player", "referer", "userid"} {
		q.Del(k)
	}
	u.RawQuery = q.Encode()
	return u.String()
}
